version: '3'

services:
  # PHP Apache Web Server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sellingvga_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: sellingvga_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: htvga
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./htvga.sql:/docker-entrypoint-initdb.d/htvga.sql

volumes:
  mysql_data:
